name:                hhuffman-tree
version:             0.1.0.0
github:              "brenoafb/hhuffman-tree"
license:             BSD3
author:              "Breno Fatureto"
maintainer:          "breno.afb@gmail.com"
copyright:           "2021 Breno Fatureto"

extra-source-files:
- README.md
- ChangeLog.md
- containers

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/brenoafb/hhuffman-tree#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- bytestring
- binary

library:
  source-dirs: src

executables:
  hhuffman-tree-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hhuffman-tree

tests:
  hhuffman-tree-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hhuffman-tree
